version: "3.1"
services:
  mydb:
    build: ./mysql
    container_name: "mydb"
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  myredis:
    build: ./redis
    container_name: "myredis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
      - /etc/localtime:/etc/localtime:ro
  myphp:
    build: ./php
    build: ./php
    container_name: "myphp"
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - /etc/localtime:/etc/localtime:ro
    links:
      - "mydb"
      - "myredis"

  mynginx:
    container_name: "mynginx"
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - "myphp"
    volumes:
      - ./www:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx.log:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl
      - /etc/localtime:/etc/localtime:ro
    restart: always
