version: "3.1"
# 服务列表
services:
  mydb:
    build: ./mysql
    container_name: "mydb"
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  myredis:
    build: ./redis
    container_name: "myredis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  myphp:
    build: ./php
    build: ./php
    container_name: "myphp"
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    links:
      - "mydb"
      - "myredis"

  mynginx:
    container_name: "mynginx"
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - "myphp"
    volumes:
      - ./www:/var/www/html
      # ngin的配置文件
      - ./nginx/conf.d:/etc/nginx/conf.d
      # 配置nginx的log目录，方便查看
      - ./logs/nginx.log:/var/log/nginx
      # 配置nginx的ssl目录
      - ./nginx/ssl:/etc/nginx/ssl
    restart: always
